### PR TITLE
chore: add bump_deps action using ncu

### PR DESCRIPTION
**Pull request by aminya**
This uses ncu instead of the dependent bot which offers more control and flexibility.

We need to remove the dependent bot after this.

Closes #92 Closes #91

### CODE REVIEW

**Comment by UziTech** [comment]
This action won't run the tests when the PR is created if we use `GITHUB_TOKEN` to create it.

**Comment by aminya** [comment]
I'll merge this since we have been using it in other repositories. Testing it in action requires waiting until the bot getting actually triggered.

**Comment by aminya** [comment]
> This action won't run the tests when the PR is created if we use `GITHUB_TOKEN` to create it.

Should I remove GITHUB_TOKEN?

**Comment by UziTech** [comment]
We should use a different token.

**Comment by UziTech** [comment]
it defaults to `GITHUB_TOKEN` if we don't provide one.

**Comment by aminya** [comment]
I am OK with using a token. These actions are safe and are widely used by the community.

**Comment by UziTech** [comment]
If you have access to @atom-ide-community-bot we should use that account

**Comment by UziTech** [comment]
You could create an organization secret with the PAT something like `GH_TOKEN`

**Comment by aminya** [comment]
Unfortunately, I don't have access to that bot. I can create the token by my own account.

**Comment by UziTech** [comment]
that will work too.

**Comment by UziTech** [comment]
FYI here is the information about why it doesn't run tests with `GITHUB_TOKEN`

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token

**Comment by aminya** [comment]
The action suggests creating a GitHub app: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens

**Comment by UziTech** [comment]
That could work too.

**Comment by aminya** [comment]
The lock file on the master seems old. I'll remove and generate it again.

**Pull request merged**
